FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY blog_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/blog_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY blog_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/blog_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY blog_app.py /home/myapp/
EXPOSE 0527
CMD python3 /home/myapp/blog_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY blog_app.py /home/myapp/
EXPOSE 0527
CMD python3 /home/myapp/blog_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY blog_app.py /home/myapp/
EXPOSE 0527
CMD python3 /home/myapp/blog_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY blog_app.py /home/myapp/
EXPOSE 5270
CMD python3 /home/myapp/blog_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
EXPOSE 5271
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
COPY ./static/img /home/myapp/static/img/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
COPY ./static/img /home/myapp/static/img/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
COPY ./static/img /home/myapp/static/img/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
COPY ./static/img /home/myapp/static/img/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
COPY ./static/img /home/myapp/static/img/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY cats.py /home/myapp/
COPY ./static/img /home/myapp/static/img/
EXPOSE 5270
CMD python3 /home/myapp/cats.py
