version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8070:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: wordpress2023
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress:
  db_data:

networks:
  default: 
    name: mi_cms
    external: false
