# Generated by Django 4.2.7 on 2023-11-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customer_phone_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='operator_name',
            new_name='operator_id',
        ),
    ]
