# Generated by Django 4.2.7 on 2023-11-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_customer_name_order_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='operator_id',
            new_name='operator_name',
        ),
    ]
