# Generated by Django 4.2.7 on 2023-11-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_created_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_order',
            field=models.DateField(),
        ),
    ]
