# Generated by Django 4.2.7 on 2023-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_order_id_bill_order_remove_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identification',
            field=models.PositiveBigIntegerField(default=True),
        ),
    ]
