# Generated by Django 4.2.7 on 2023-11-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_customer_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.PositiveBigIntegerField(editable=False),
        ),
    ]
