# Generated by Django 4.2.7 on 2023-11-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bill_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='discount',
        ),
    ]
